import Appcontext from "@/app/context/Appcontext";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Appcontext>{children}</Appcontext>
      </body>
    </html>
  );
}
